FROM python:3.10-slim

# Add code location code
WORKDIR /opt/dagster/app
RUN mkdir -p /opt/dagster/app/sensor_data_mlops
RUN mkdir -p /opt/dagster/app/data
RUN mkdir -p /opt/dagster/app/keys
COPY /sensor_data_mlops ./sensor_data_mlops
COPY pyproject.toml ./pyproject.toml

RUN ["pip", "install", "-e", "."]

# Run dagster code server on port 4000
EXPOSE 4000

# CMD allows this to be overridden from run launchers or executors to execute runs and steps
CMD ["dagster", "code-server", "start", "-h", "0.0.0.0", "-p", "4000", "-f", "sensor_data_mlops/definitions.py"]